build:
  nodes:
     my-node:
      services:
        mongo: 4
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
