language: node_js

node_js:
    - "node"
    - "lts/*"
    - "11"
    - "10"

sudo: false

services:
  - mongodb

git:
    submodules: false

before_script:
    - npm install
    - sleep 15
    - mongo testtrading --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
    - npm test

after_success:
  - npm run coverage