language: node_js

node_js:
    - "node"
    - "lts/*"
    - "11"
    - "10"

sudo: false

services:
  - mongodb

git:
    submodules: false

before_script:
    - npm install
    - sleep 15

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
