language: node_js

node_js:
    - "node"
    - "lts/*"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

before_script:
    - sleep 15
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov